### ISSUE TITLE
Step by step instructions

### ISSUE THREAD

**Issue by rajdhandus** [witnessmenow/arduino-traffic-notifier#2]
I am trying to setup something like this to monitor and notify if the time take from Home to Work (or vice versa) crosses a certain threshold.. Do you possibly have step by step instructions documented somewhere?

**Comment by witnessmenow** [comment]
Hey,

Have you seen the YouTube video related to this project?

https://youtu.be/KjIRUTPcvCQ

It explains how to get the keys etc.

And then you could check out my video on sending notifications from your
esp8266

https://youtu.be/yFiKDabYJ1I



On 16 May 2017 16:29, "Rajkumar Purushothaman" <notifications@github.com>
wrote:

I am trying to setup something like this to monitor and notify if the time
take from Home to Work (or vice versa) crosses a certain threshold.. Do you
possibly have step by step instructions documented somewhere?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/witnessmenow/arduino-traffic-notifier/issues/2>, or mute
the thread

**Comment by rajdhandus** [comment]
thanks for your reply.. i will check out those links..
